Add JWT app, subscriptions app, update user
drode1/pay2u_backend pull request #2
Opened 2024-03-24 13:35 UTC by bikovshanin

- Добавил приложение для генерации токена
- Дополнил модель пользователя добавил едпоит для передачи данных пользователя, пока без пермишена, админку для пользователя поправил
- Добавил приложение subscriptions, там пока только модели

2024-03-24 17:54 UTC, drode1 requested changes
1. Поправь, пожалуйста, те моменты что написал
2. После этого, я проверю еще раз и если ок, смержим в main ветку, остальные правки уже в отдельной ветке будет делать

2024-03-24 17:54 UTC, drode1 commented on app/auth_jwt/api/serializers.py
> +class TokenSerializer(serializers.ModelSerializer):
1. TokenOutputSerializer
2. Мы токен же не от модели пользователя получаем, нужно поправить наследование

2024-03-24 17:54 UTC, drode1 commented on app/auth_jwt/api/serializers.py
> +        fields = ('id',)
Лишнее, т.к. мы не наследуемая от модели

2024-03-24 17:54 UTC, drode1 commented on app/auth_jwt/api/urls.py
> +app_name = 'auth_jwt'
Можно просто auth назвать, как и само приложение

2024-03-24 17:54 UTC, drode1 commented on app/auth_jwt/api/views.py
> +User = get_user_model()
```suggestion
from app.users.models import User
```

2024-03-24 17:54 UTC, drode1 commented on app/auth_jwt/api/views.py
> +            )
Вообще, лучше сделать так:
1. Вынести в services.py функцию get_user_by_id -> и вернуть пользователя
2. Можно сделать просто через get_object_or_404()

2024-03-24 17:54 UTC, drode1 commented on app/auth_jwt/api/views.py
> +        print(request.user)
Принты нужно убирать

2024-03-24 17:54 UTC, drode1 commented on app/auth_jwt/api/views.py
> +        token = RefreshToken.for_user(user)
Сделай отдельную функцию в services.py, которая принимает юзера и возвращает два токена, и их возвращай в респонсе

2024-03-24 17:54 UTC, drode1 commented on app/auth_jwt/apps.py
> +    verbose_name = 'AuthJWT'
лучше как JWT Auth

2024-03-24 17:54 UTC, drode1 commented on app/auth_jwt/models.py
> +from django.db import models
Если файл будет пустой, давай удалим его, зачем плодить лишнее

2024-03-24 17:54 UTC, drode1 commented on app/auth_jwt/admin.py
> +from django.contrib import admin
Если файл будет пустой, давай удалим его, зачем плодить лишнее

2024-03-24 17:54 UTC, drode1 commented on app/auth_jwt/api/serializers.py
> +User = get_user_model()
```suggestion
from app.users.models import User
```

2024-03-24 17:54 UTC, drode1 commented on app/subscriptions/models.py
> +class Category(models.Model):
Давай наследоваться от базовой модели из cors
```suggestion
class Category(BaseModel):
```

2024-03-24 17:54 UTC, drode1 commented on app/subscriptions/models.py
> +class Cashback(models.Model):
```suggestion
class Cashback(BaseModel):
```

2024-03-24 17:54 UTC, drode1 commented on app/subscriptions/models.py
> +        'category name',
Мы ведь и так знаем что эта категория, можно просто как Name оставить или ничего не писать

2024-03-24 17:54 UTC, drode1 commented on app/subscriptions/models.py
> +        null=False
В идеале лучше явно еще прописывать атрибуты blank=False

2024-03-24 17:54 UTC, drode1 commented on app/subscriptions/models.py
> +        'cashback amount',
Мы ведь и так знаем что эта кол-во, можно просто как Amount оставить или ничего

2024-03-24 17:54 UTC, drode1 commented on app/subscriptions/models.py
> +class Invoice(models.Model):
```suggestion
class Invoice(BaseModel):
```

2024-03-24 17:54 UTC, drode1 commented on app/subscriptions/models.py
> +        'invoice amount',
писал выше

2024-03-24 17:54 UTC, drode1 commented on app/subscriptions/models.py
> +        blank=True,
А точно?)

дата счета ведь всегда будет

2024-03-24 17:54 UTC, drode1 commented on app/subscriptions/models.py
> +        auto_now=True,
Вот тут лучше свериться с девочками, по какому сценарию формируется счет

2024-03-24 17:54 UTC, drode1 commented on app/users/api/serializers.py
> +            'cashback_mounth'
```suggestion
            'cashback_mounth',
```

2024-03-24 17:54 UTC, drode1 commented on app/users/api/serializers.py
> +        return 0
Ну давай вместо return 0 отдавать raise NotImplemented

2024-03-24 17:54 UTC, drode1 commented on app/users/api/urls.py
>  #     path('me/', DetailUserMeAPI.as_view(), name='self'),
А это не хочешь вернуть?)

2024-03-24 17:54 UTC, drode1 commented on app/users/models.py
> +        'email address',
```suggestion
        'email',
```

2024-03-24 17:54 UTC, drode1 commented on app/users/models.py
> +        unique=True
```suggestion
        unique=True,
        blank=False,
        null=False,
```

2024-03-24 17:54 UTC, drode1 commented on app/users/models.py
> +        'first name',
```suggestion
        'First name',
```

2024-03-24 17:54 UTC, drode1 commented on app/users/models.py
> +        max_length=20,
Такие штуки лучше вынести в настройки. И почему именно 20?)

2024-03-24 17:54 UTC, drode1 commented on app/users/models.py
> +        'notification date',
Комментарий выше оставил для подобного

2024-03-24 17:54 UTC, drode1 commented on app/users/models.py
> +        'phone'
```suggestion
        'phone',
```

2024-03-24 17:54 UTC, drode1 commented on config/django/base.py
> +
Нет нет, у тебя для этого есть config/settings/rest_framework.py

2024-03-24 17:54 UTC, drode1 commented on config/django/base.py
> +}
Создай config/settings/jwt.py и туда вынеси, сюда просто импортируй

2024-03-24 17:54 UTC, drode1 commented on config/urls.py
> +    path('', include((token_urlpatterns, 'auth_jwt'))),
```suggestion
    path('login/', include((token_urlpatterns, 'auth_jwt'))),
```

2024-03-25 07:48 UTC, bikovshanin commented on app/auth_jwt/api/urls.py
> +app_name = 'auth_jwt'
Я пробовал назвать просто auth, при миграциях ошибки вылазят, конфликт имён

2024-03-25 14:28 UTC, drode1 requested changes

2024-03-25 14:28 UTC, drode1 commented on app/core/services.py
> +    return user
```suggestion
def get_user_by_id(id: int):
        user = get_object_or_404(User, id)
    return user
```

2024-03-25 14:28 UTC, drode1 commented on app/core/services.py
> +                    status=status.HTTP_201_CREATED)
```suggestion
def get_tokens(user: User):
    token = RefreshToken.for_user(user)
    
    return token, token.access_token
```

2024-03-25 14:28 UTC, drode1 commented on app/auth_jwt/api/views.py
> +        return get_token(user)
Ниже поправил твой метод с получением токена
сделай примерно такое лучше
refresh_token, access_token = get_tokens(user)
response = {
"access": access_token,
"refresh": refresh_token
}

2024-03-25 14:28 UTC, drode1 commented on app/users/models.py
> +        max_length=20,
А почему max_length то не вынес? Сделай дефолтное 255 (в настройках должно быть) или просто заведи свою отдельную переменную Если тебе везде менять 20 потом, лучше поменять в одном месте, чем по всему проекту

2024-03-26 08:34 UTC, merged